version: '3.3'
services:
    dnsmasq:
        cap_add:
        - NET_ADMIN
        image: quay.io/poseidon/dnsmasq:v0.5.0-21-gbbda3b9
        ports:
        - 69:69/tcp
        - 69:69/udp
        restart: always
        command:
        - -d
        - -q
        - --dhcp-range=192.168.1.1,proxy,255.255.255.0
        - --enable-tftp
        - --tftp-root=/var/lib/tftpboot
        - --dhcp-userclass=set:ipxe,iPXE
        - --pxe-service=tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe
        - --pxe-service=tag:ipxe,x86PC,"iPXE",http://matchbox.tsuzu.dev:28080/boot.ipxe
        - --pxe-service=tag:#ipxe,X86-64_EFI,"PXE chainload to iPXE UEFI",ipxe.efi
        - --pxe-service=tag:ipxe,X86-64_EFI,"iPXE UEFI",http:///matchbox.tsuzu.dev:28080/boot.ipxe
        - --log-queries
        - --log-dhcp
    matchbox:
        image: quay.io/poseidon/matchbox:v0.9.1-62-g8765e07b
        network_mode: host
        volumes:
        - ./files:/var/lib/matchbox/assets:Z
        - ./config:/etc/matchbox:Z,ro
        restart: always
        command:
        - -address=0.0.0.0:28080
        - -rpc-address=0.0.0.0:28081
        - -log-level=debug
    setup-certs:
        image: ubuntu:22.04
        volumes:
        - ./config:/etc/matchbox:Z
        restart: "no"
        command:
        - bash
        - -c 
        - >
            ls /etc/matchbox/server.crt ||
            (apt-get update &&
            apt-get install -y --no-install-recommends git openssl ca-certificates &&
            git clone https://github.com/poseidon/matchbox.git &&
            cd matchbox/scripts/tls &&
            SAN=DNS.1:matchbox.tsuzu.dev,IP.1:192.168.1.22 ./cert-gen &&
            cp ca.crt server.crt server.key /etc/matchbox)
